// Auto-generated by scripts/generate-textures.mjs
// Do not edit manually. Run: node scripts/generate-textures.mjs

export type TextureFiles = {
  albedo?: string;
  normal?: string;
  roughness?: string;
  ao?: string;
};

export const AVAILABLE_TEXTURES: Record<string, TextureFiles> = {
  "clasic": {
    "albedo": "/models/textures/clasic.png",
    "ao": "/models/textures/clasic_ao.png",
    "normal": "/models/textures/clasic_normal.png"
  }
};
