// Auto-generated by scripts/generate-decorations.mjs
// Do not edit manually. Run: node scripts/generate-decorations.mjs

export type GeneratedDecoration = {
  id: string;
  name: string;
  path: string;
  scale: number;
};

export const AVAILABLE_DECORATIONS: GeneratedDecoration[] = [
  {
    "id": "roca1",
    "name": "Roca1",
    "path": "/models/decorations/roca1.glb",
    "scale": 1
  }
];
